version: "3.10"
services:
  app:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/python-flaskversion: "3.10"
services:
  app:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/python-flask